<?php

namespace App\Models;

use Database\Factories\InviteFactory;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * A single-use invite code (Phase 11). Valid iff used_at is null.
 *
 * Codes are generated by `invite:generate` and consumed exactly once during
 * registration. used_at / used_by_id are deliberately not fillable — they
 * are stamped by RegisteredUserController's guarded update only.
 */
#[Fillable(['code', 'note'])]
class Invite extends Model
{
    /** @use HasFactory<InviteFactory> */
    use HasFactory;

    /**
     * Every character here survives handwriting and bad fonts: no 0/O,
     * no 1/l/I. 57 characters at 12 positions is ~70 bits of entropy —
     * unguessable through a throttled endpoint by a comfortable margin.
     */
    public const ALPHABET = '23456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';

    public const CODE_LENGTH = 12;

    protected function casts(): array
    {
        return [
            'used_at' => 'datetime',
        ];
    }

    public function isUsed(): bool
    {
        return $this->used_at !== null;
    }

    /**
     * The account this code created, if it has been used.
     *
     * @return BelongsTo<User, $this>
     */
    public function usedBy(): BelongsTo
    {
        return $this->belongsTo(User::class, 'used_by_id');
    }

    /**
     * A fresh, unique bare code (no dashes — display formatting is separate).
     */
    public static function generateCode(): string
    {
        do {
            $code = '';
            for ($i = 0; $i < self::CODE_LENGTH; $i++) {
                $code .= self::ALPHABET[random_int(0, strlen(self::ALPHABET) - 1)];
            }
            // A collision is astronomically unlikely at 70 bits; the loop is
            // a belt to the unique constraint's suspenders.
        } while (self::where('code', $code)->exists());

        return $code;
    }

    /**
     * The human-friendly form codes are distributed in: Xxxx-Xxxx-Xxxx.
     */
    public function displayCode(): string
    {
        return implode('-', str_split($this->code, 4));
    }

    /**
     * Strip the display formatting (dashes, stray whitespace) from user
     * input before lookup. Case is preserved — codes are case-sensitive.
     */
    public static function normalize(string $input): string
    {
        return preg_replace('/[\s-]+/', '', $input);
    }
}
